apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.37.1
          name: prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            # Mount the config file from ConfigMap (single file mount with subPath)
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            # Mount the PVC volume as directory for prometheus data storage
            - name: prometheus-claim0
              mountPath: /prometheus
      volumes:
        # ConfigMap volume containing prometheus.yml
        - name: config-volume
          configMap:
            name: prometheus-config
        # PVC volume for persistent data storage
        - name: prometheus-claim0
          persistentVolumeClaim:
            claimName: prometheus-claim0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus-claim0
  name: prometheus-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
